from __future__ import annotations

import json
from math import exp, log
from pathlib import Path

import numpy as np
import pytest

CASE_PATH = Path(__file__).parents[1] / "frontend" / "src" / "data" / "explainability_case.json"
MODEL_ARTIFACTS = (
    CASE_PATH.parents[3] / "models" / "best_model.joblib",
    CASE_PATH.parents[3] / "models" / "model_metadata.json",
    CASE_PATH.parents[3] / "models" / "artifact_manifest.json",
)


def _skip_without_model_artifacts() -> None:
    if not all(path.is_file() for path in MODEL_ARTIFACTS):
        pytest.skip("model artifacts are generated by the integration pipeline job")


def test_case_study_provenance_and_reconstruction() -> None:
    from src.contracts import (
        CALIBRATION_STATUS,
        DECISION_THRESHOLD,
        RAW_TARGET_TO_LABEL,
        SAFETY_POSITIVE_LABEL,
        SAFETY_POSITIVE_RAW_TARGET,
    )
    from src.data.load_dataset import load_dataset_frame
    from src.features.preprocess import split_dataset

    artifact = json.loads(CASE_PATH.read_text(encoding="utf-8"))
    bundle = load_dataset_frame()
    splits = split_dataset(bundle.features, bundle.target, seed=42)

    assert artifact["schema_version"] == 1
    assert artifact["dataset_row_id"] == 102
    assert 102 in splits.X_test.index
    assert artifact["raw_target"] == int(bundle.target.loc[102]) == 1
    assert artifact["known_label"] == RAW_TARGET_TO_LABEL[artifact["raw_target"]] == "benign"
    assert artifact["model_name"] == "logistic_regression"
    assert isinstance(artifact["model_version"], str) and artifact["model_version"]
    assert artifact["positive_class"] == SAFETY_POSITIVE_LABEL == "malignant"
    assert artifact["output_space"] == "malignant_class_log_odds"
    assert artifact["threshold"] == DECISION_THRESHOLD == 0.5
    assert artifact["calibration_status"] == CALIBRATION_STATUS == "uncalibrated"
    assert artifact["feature_order"] == bundle.feature_names
    assert artifact["feature_count"] == len(bundle.feature_names) == 30
    assert len(artifact["contributions"]) == 30
    assert "model_score_logit" not in artifact

    contributions = artifact["contributions"]
    assert [item["rank"] for item in contributions] == list(range(1, 31))
    assert [item["feature"] for item in contributions] == [
        item["feature"]
        for item in sorted(
            contributions,
            key=lambda item: (-item["absolute_contribution"], item["rank"]),
        )
    ]
    assert all(
        item["direction"]
        == (
            "toward_malignant"
            if item["contribution"] > 0
            else "away_from_malignant"
            if item["contribution"] < 0
            else "neutral"
        )
        for item in contributions
    )
    finite_values = [
        artifact["base_value"],
        artifact["contribution_sum"],
        artifact["reconstructed_log_odds"],
        artifact["model_score"],
        artifact["reconstruction_error"],
        *[value for item in contributions for value in item.values() if isinstance(value, float)],
    ]
    assert np.isfinite(finite_values).all()

    reconstructed = artifact["base_value"] + artifact["contribution_sum"]
    assert np.isclose(artifact["reconstructed_log_odds"], reconstructed, atol=1e-9)

    assert SAFETY_POSITIVE_RAW_TARGET == 0
    model_score = float(artifact["model_score"])
    expected_log_odds = log(model_score / (1.0 - model_score))
    assert np.isclose(artifact["reconstructed_log_odds"], expected_log_odds, atol=1e-9)
    assert np.isclose(
        artifact["model_score"],
        1.0 / (1.0 + exp(-artifact["reconstructed_log_odds"])),
        atol=1e-9,
    )
    assert artifact["reconstruction_error"] <= artifact["reconstruction_tolerance"]


def test_case_study_check_matches_current_model_artifacts() -> None:
    _skip_without_model_artifacts()

    from src.explainability.case_study import verify_case_study_artifact

    verify_case_study_artifact(CASE_PATH)


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("model_version", "stale-version"),
        ("model_score", 0.5),
    ],
)
def test_case_study_check_rejects_stale_provenance(
    tmp_path: Path, field: str, value: object
) -> None:
    _skip_without_model_artifacts()

    from src.explainability.case_study import verify_case_study_artifact

    candidate = json.loads(CASE_PATH.read_text(encoding="utf-8"))
    candidate[field] = value
    candidate_path = tmp_path / "explainability_case.json"
    candidate_path.write_text(json.dumps(candidate), encoding="utf-8")

    with pytest.raises(ValueError, match="does not match"):
        verify_case_study_artifact(candidate_path)


def test_case_study_check_rejects_stale_contribution(tmp_path: Path) -> None:
    _skip_without_model_artifacts()

    from src.explainability.case_study import verify_case_study_artifact

    candidate = json.loads(CASE_PATH.read_text(encoding="utf-8"))
    candidate["contributions"][0]["contribution"] += 0.1
    candidate_path = tmp_path / "explainability_case.json"
    candidate_path.write_text(json.dumps(candidate), encoding="utf-8")

    with pytest.raises(ValueError, match="does not match"):
        verify_case_study_artifact(candidate_path)
